### PR TITLE
Add compiled library

### PR DESCRIPTION
**Pull request by psaripp**
Add the build of the latest library to the repo.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@RobotWebTools/roslibjs-maintainers The update of the build is already taken care of in the `develop` branch. But is there a reason why the exports from 569052719531d55f4a5422195d091c00138d07cf are not in `develop`?

**Comment by jihoonl** [comment]
I assume unordered a list of PRs may have missed some features. As compiled libs always creates conflicts with PRs, it would be better if it rebuilds by itself when a PR gets merged into develop. And no PR includes changes in compiled library.

**Comment by MatthijsBurgh** [comment]
@jihoonl That would indeed be a good feature of CI pipeline. But do you agree the changes of 569052719531d55f4a5422195d091c00138d07cf should be in develop?

**Comment by jihoonl** [comment]
Yes. I think #312 missed to add the exports.

**Comment by MatthijsBurgh** [comment]
Superseded by #417

**Pull request closed without merging**
