### PR TITLE
Support for different marker actions

### PR DESCRIPTION
**Pull request by daniel86**
Support for different marker actions.
Also implemented a basic update method for markers that allows
to dynamically change the pose and color of markers.

### CODE REVIEW

**Comment by rctoris** [comment]
Great, thanks! Will test it out this week.

**Comment by rctoris** [comment]
Can you also make this PR into the `develop` branch instead of `master`?

**Comment by daniel86** [comment]
Sure, will do this later today

**Comment by rctoris** [comment]
replaced by https://github.com/RobotWebTools/ros3djs/pull/97

**Pull request closed without merging**
